name: ci_01
on: workflow_dispatch

jobs:
  info-sys:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: affiche stok
        run: lsblk
      - name: info distro
        run: uname -a

