name: ci_01
on: workflow_dispash

jobs:
  info-sys:
    runs-on: ubuntu-latest
    steps:
      - name: fqdn du serveur
        run: hostnamectl
      - name: info ipv4
        run: hostname -I
      - name: whoiam
        run: whoami

